-- Insert statements for the swissdev-tracker companies table
-- Based on the Prisma schema

INSERT INTO companies (name, description, industry, size, location, website, founded, logo, benefits, "openPositions", rating, "createdAt", "updatedAt")
VALUES
    ('UBS', 'Global financial services firm providing investment banking, asset management, and wealth management services worldwide.', 'Financial Services', 'Large (10,000+)', 'Zurich, Switzerland', 'https://www.ubs.com', 1862, 'https://logo.clearbit.com/ubs.com', ARRAY['Health Insurance', 'Pension Plan', 'Flexible Working', 'Professional Development', 'Stock Options'], 0, 4.2, NOW(), NOW()),
    ('Nestlé', 'World''s largest food and beverage company, committed to enhancing quality of life and contributing to a healthier future.', 'Consumer Goods', 'Large (10,000+)', 'Vevey, Switzerland', 'https://www.nestle.com', 1866, 'https://logo.clearbit.com/nestle.com', ARRAY['Health Insurance', 'Pension Plan', 'Flexible Working', 'Global Opportunities', 'Learning Budget'], 0, 4.2, NOW(), NOW()),
    ('Credit Suisse', 'Leading global financial services company offering private banking, investment banking and asset management services.', 'Financial Services', 'Large (10,000+)', 'Basel, Switzerland', 'https://www.credit-suisse.com', 1856, 'https://logo.clearbit.com/credit-suisse.com', ARRAY['Health Insurance', 'Pension Plan', 'Bonus Scheme', 'Training Programs', 'Flexible Hours'], 0, 4.0, NOW(), NOW()),
    ('Roche', 'Global pioneer in pharmaceuticals and diagnostics focused on advancing science to improve people''s lives.', 'Pharmaceuticals', 'Large (10,000+)', 'Basel, Switzerland', 'https://www.roche.com', 1896, 'https://logo.clearbit.com/roche.com', ARRAY['Health Insurance', 'Life Insurance', 'Flexible Working', 'Research Opportunities', 'Professional Development'], 0, 4.4, NOW(), NOW()),
    ('Swisscom', 'Switzerland''s leading telecommunications company providing mobile, internet, and digital services.', 'Telecommunications', 'Large (10,000+)', 'Bern, Switzerland', 'https://www.swisscom.ch', 1998, 'https://logo.clearbit.com/swisscom.ch', ARRAY['Health Insurance', 'Pension Plan', 'Mobile Benefits', 'Flexible Working', 'Training Programs'], 0, 4.1, NOW(), NOW()),
    ('Google Zurich', 'Google''s largest engineering office outside the US, developing products used by billions including Search, Gmail, and YouTube.', 'Technology', 'Large (1,000-10,000)', 'Zurich, Switzerland', 'https://www.google.com', 2004, 'https://logo.clearbit.com/google.com', ARRAY['Health Insurance', 'Stock Options', 'Free Meals', 'Flexible Working', 'Learning Budget'], 0, 4.6, NOW(), NOW()),
    ('Logitech', 'Swiss-American company designing and manufacturing computer peripherals and software.', 'Technology', 'Medium (100-1,000)', 'Lausanne, Switzerland', 'https://www.logitech.com', 1981, 'https://logo.clearbit.com/logitech.com', ARRAY['Health Insurance', 'Stock Options', 'Flexible Working', 'Innovation Time', 'Professional Development'], 0, 4.3, NOW(), NOW()),
    ('EPFL Innovation Park', 'Technology park and innovation ecosystem connected to École Polytechnique Fédérale de Lausanne.', 'Research & Education', 'Medium (100-1,000)', 'Lausanne, Switzerland', 'https://www.epfl.ch', 1969, 'https://logo.clearbit.com/epfl.ch', ARRAY['Health Insurance', 'Research Opportunities', 'Flexible Working', 'Learning Budget', 'Innovation Projects'], 0, 4.5, NOW(), NOW()),
    ('Digitec Galaxus', 'Switzerland''s largest online retailer for electronics, home & garden, sports, and many other product categories.', 'E-commerce', 'Medium (100-1,000)', 'Zurich, Switzerland', 'https://www.digitec.ch', 2001, 'https://logo.clearbit.com/digitec.ch', ARRAY['Health Insurance', 'Employee Discounts', 'Flexible Working', 'Learning Budget', 'Modern Office'], 0, 4.4, NOW(), NOW()),
    ('ABB', 'Leading global technology company that energizes the transformation of society and industry.', 'Industrial Technology', 'Large (10,000+)', 'Baden, Switzerland', 'https://www.abb.com', 1988, 'https://logo.clearbit.com/abb.com', ARRAY['Health Insurance', 'Pension Plan', 'Flexible Working', 'Learning Budget', 'Professional Development'], 0, 4.2, NOW(), NOW());