INSERT INTO jobs (title, company, location, type, salary, description, requirements, "postedDate", status, "createdAt", "updatedAt")
VALUES
    ('Senior Full Stack Developer', 1, 'Zurich, Switzerland', 'FULL_TIME', 'CHF 120,000 - 140,000', 'Join our fintech team to build cutting-edge banking solutions using modern web technologies.', ARRAY['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS', '5+ years experience'], NOW() - INTERVAL '2 days', 'ACTIVE', NOW(), NOW()),
    ('Frontend Developer (React)', 2, 'Vevey, Switzerland', 'FULL_TIME', 'CHF 95,000 - 115,000', 'Develop responsive web applications for our global consumer brands.', ARRAY['React', 'JavaScript', 'CSS3', 'HTML5', 'Redux', 'Git', '3+ years experience'], NOW() - INTERVAL '1 day', 'ACTIVE', NOW(), NOW()),
    ('Backend Engineer (Java)', 3, 'Basel, Switzerland', 'FULL_TIME', 'CHF 110,000 - 130,000', 'Build scalable microservices for our trading platform.', ARRAY['Java', 'Spring Boot', 'Microservices', 'Apache Kafka', 'Docker', 'Kubernetes'], NOW() - INTERVAL '3 days', 'ACTIVE', NOW(), NOW()),
    ('DevOps Engineer', 4, 'Basel, Switzerland', 'FULL_TIME', 'CHF 115,000 - 135,000', 'Manage cloud infrastructure and CI/CD pipelines for our pharmaceutical research platform.', ARRAY['AWS', 'Docker', 'Kubernetes', 'Terraform', 'Jenkins', 'Python', 'Linux'], NOW() - INTERVAL '1 week', 'ACTIVE', NOW(), NOW()),
    ('Mobile App Developer', 5, 'Bern, Switzerland', 'FULL_TIME', 'CHF 100,000 - 120,000', 'Develop mobile applications for Switzerland''s leading telecom provider.', ARRAY['Swift', 'Kotlin', 'React Native', 'iOS SDK', 'Android SDK', 'REST APIs'], NOW() - INTERVAL '5 days', 'ACTIVE', NOW(), NOW()),
    ('Data Scientist', 6, 'Zurich, Switzerland', 'FULL_TIME', 'CHF 140,000 - 180,000', 'Build and deploy machine learning models at scale.', ARRAY['Python', 'TensorFlow', 'GCP', 'Machine Learning', 'Statistics', '5+ years experience'], NOW() - INTERVAL '6 days', 'ACTIVE', NOW(), NOW()),
    ('UX Designer',  7, 'Lausanne, Switzerland', 'FULL_TIME', 'CHF 90,000 - 110,000', 'Design user experiences for next-generation computer peripherals.', ARRAY['Figma', 'Adobe Creative Suite', 'User Research', 'Prototyping', 'Design Systems'], NOW() - INTERVAL '4 days', 'ACTIVE', NOW(), NOW()),
    ('Software Engineering Intern', 8, 'Lausanne, Switzerland', 'INTERNSHIP', 'CHF 1,800 - 2,200 per month', 'Join our research team as a software engineering intern.', ARRAY['Python', 'Git', 'Currently studying Computer Science', 'English fluency'], NOW() - INTERVAL '1 week', 'ACTIVE', NOW(), NOW()),
    ('React Developer', 9, 'Zurich, Switzerland', 'CONTRACT', 'CHF 700 - 900 per day', 'Short-term contract to enhance our e-commerce platform.', ARRAY['React', 'TypeScript', 'Node.js', 'API Integration', '3+ years experience'], NOW() - INTERVAL '2 days', 'ACTIVE', NOW(), NOW()),
    ('Quality Assurance Engineer', 10, 'Baden, Switzerland', 'FULL_TIME', 'CHF 85,000 - 105,000', 'Test and ensure quality of industrial automation software.', ARRAY['Test Automation', 'Selenium', 'Java', 'API Testing', 'Agile Testing'], NOW() - INTERVAL '3 days', 'ACTIVE', NOW(), NOW());
